scrapy crawl multi_spider -a url='https://www.allphenoms.com' -a domain='allphenoms.com' -O .\files\AllPhenoms.csv --nolog
scrapy crawl multi_spider -a url='https://www.almased.com' -a domain='almased.com' -O .\files\AlmasedUSA,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.americanbiosciences.com' -a domain='americanbiosciences.com' -O .\files\AmericanBioSciences,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.amerilabtech.com' -a domain='amerilabtech.com' -O .\files\AmerilabTechnologies,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.ancientnutrition.com' -a domain='ancientnutrition.com' -O .\files\AncientNutrition.csv --nolog
scrapy crawl multi_spider -a url='https://www.angelyeast.com' -a domain='angelyeast.com' -O .\files\AngelYeastCo.,Ltd.csv --nolog
scrapy crawl multi_spider -a url='https://www.arthurandrew.com' -a domain='arthurandrew.com' -O .\files\ArthurAndrewMedical.csv --nolog
scrapy crawl multi_spider -a url='https://www.aussiebubs.com' -a domain='aussiebubs.com' -O .\files\AussieBubs,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.ayoyogurt.com' -a domain='ayoyogurt.com' -O .\files\AyoYogurt.csv --nolog
scrapy crawl multi_spider -a url='https://www.bakeryonmain.com' -a domain='bakeryonmain.com' -O .\files\BakeryonMain.csv --nolog
scrapy crawl multi_spider -a url='https://www.balaenzyme.com' -a domain='balaenzyme.com' -O .\files\BalaEnzyme,Inc.csv --nolog
scrapy crawl multi_spider -a url='https://www.belliwelli.com' -a domain='belliwelli.com' -O .\files\BelliWelli.csv --nolog
scrapy crawl multi_spider -a url='https://www.bellwetherfarms.com' -a domain='bellwetherfarms.com' -O .\files\BellwetherFarms.csv --nolog
scrapy crawl multi_spider -a url='https://www.betterbooch.com' -a domain='betterbooch.com' -O .\files\BetterBooch.csv --nolog
scrapy crawl multi_spider -a url='https://www.bevpax.com' -a domain='bevpax.com' -O .\files\Bevpax.csv --nolog
scrapy crawl multi_spider -a url='https://www.lgreenhealth.com' -a domain='lgreenhealth.com' -O .\files\BFSumaPharmaceuticalsInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.bfreefoods.com' -a domain='bfreefoods.com' -O .\files\BFreeFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.bigpicturefoods.com' -a domain='bigpicturefoods.com' -O .\files\BigPictureFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.birdmanlife.com' -a domain='birdmanlife.com' -O .\files\BIRDMANLIFE.csv --nolog
scrapy crawl multi_spider -a url='https://www.bluebonnetnutrition.com' -a domain='bluebonnetnutrition.com' -O .\files\BluebonnetNutritionCorp..csv --nolog
scrapy crawl multi_spider -a url='https://www.bonafideprovisions.com' -a domain='bonafideprovisions.com' -O .\files\BonafideProvisions.csv --nolog
scrapy crawl multi_spider -a url='https://www.bossabars.com' -a domain='bossabars.com' -O .\files\BossaBars,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.bpiequip.com' -a domain='bpiequip.com' -O .\files\BPIEquipmentInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.bradsplantbased.com' -a domain='bradsplantbased.com' -O .\files\Brad'sPlantBased.csv --nolog
scrapy crawl multi_spider -a url='https://www.bragg.com' -a domain='bragg.com' -O .\files\BraggLiveFoodProducts,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.bubbies.com' -a domain='bubbies.com' -O .\files\BubbiesFineFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.caffeinearmy.com' -a domain='caffeinearmy.com' -O .\files\CaffeineArmyLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.mychaidiaries.com' -a domain='mychaidiaries.com' -O .\files\ChaiDiaries.csv --nolog
scrapy crawl multi_spider -a url='https://www.charcutnuvo.com' -a domain='charcutnuvo.com' -O .\files\CharcutNuvo.csv --nolog
scrapy crawl multi_spider -a url='https://www.chaucerfoods.com' -a domain='chaucerfoods.com' -O .\files\ChaucerFoods,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.chenland.com' -a domain='chenland.com' -O .\files\ChenlandNutritionals,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.drinkchiki.com' -a domain='drinkchiki.com' -O .\files\ChikiChikiBoomBoom.csv --nolog
scrapy crawl multi_spider -a url='https://www.childlifenutrition.com' -a domain='childlifenutrition.com' -O .\files\ChildlifeEssentials.csv --nolog
scrapy crawl multi_spider -a url='https://www.chinovabioworks.com' -a domain='chinovabioworks.com' -O .\files\ChinovaBioworks.csv --nolog
scrapy crawl multi_spider -a url='https://www.chkpfoods.com' -a domain='chkpfoods.com' -O .\files\CHKPFoodsInc.csv --nolog
scrapy crawl multi_spider -a url='https://www.cibaria-intl.com' -a domain='cibaria-intl.com' -O .\files\CibariaInternational,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.cleansimpleeats.com' -a domain='cleansimpleeats.com' -O .\files\CleanSimpleEats.csv --nolog
scrapy crawl multi_spider -a url='https://www.cliosnacks.com' -a domain='cliosnacks.com' -O .\files\ClioSnacks.csv --nolog
scrapy crawl multi_spider -a url='https://www.cocojune.co' -a domain='cocojune.co' -O .\files\CocojuneProducts.csv --nolog
scrapy crawl multi_spider -a url='https://www.coconutwhisk.com' -a domain='coconutwhisk.com' -O .\files\CoconutWhisk.csv --nolog
scrapy crawl multi_spider -a url='https://www.drinkculturepop.com' -a domain='drinkculturepop.com' -O .\files\CulturePopSoda.csv --nolog
scrapy crawl multi_spider -a url='https://www.eagleflexible.com' -a domain='eagleflexible.com' -O .\files\EAGLEFLEXIBLEPACKAGING.csv --nolog
scrapy crawl multi_spider -a url='https://www.earnesteats.com' -a domain='earnesteats.com' -O .\files\EarnestEats.csv --nolog
scrapy crawl multi_spider -a url='https://www.eclipsefoods.com' -a domain='eclipsefoods.com' -O .\files\EclipseFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.enzymedica.com' -a domain='enzymedica.com' -O .\files\Enzymedica,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.aurorainutrition.com' -a domain='aurorainutrition.com' -O .\files\EOSNutrisolutions.csv --nolog
scrapy crawl multi_spider -a url='https://www.exegipharma.com' -a domain='exegipharma.com' -O .\files\ExeGiPharma.csv --nolog
scrapy crawl multi_spider -a url='https://www.figbrew.com' -a domain='figbrew.com' -O .\files\FigBrew.csv --nolog
scrapy crawl multi_spider -a url='https://www.fineusatrading.com' -a domain='fineusatrading.com' -O .\files\FineUSATrading.csv --nolog
scrapy crawl multi_spider -a url='https://www.flavorproducers.com' -a domain='flavorproducers.com' -O .\files\FlavorProducers.csv --nolog
scrapy crawl multi_spider -a url='https://www.frieslandcampinaingredients.com' -a domain='frieslandcampinaingredients.com' -O .\files\FrieslandCampinaIngredients.csv --nolog
scrapy crawl multi_spider -a url='https://www.fytexia.com' -a domain='fytexia.com' -O .\files\Fytexia.csv --nolog
scrapy crawl multi_spider -a url='https://www.germinalorganic.com' -a domain='germinalorganic.com' -O .\files\GerminalOrganic.csv --nolog
scrapy crawl multi_spider -a url='https://www.gillco.com' -a domain='gillco.com' -O .\files\GillcoIngredients.csv --nolog
scrapy crawl multi_spider -a url='https://www.glanbianutritionals.com' -a domain='glanbianutritionals.com' -O .\files\GlanbiaNutritionals.csv --nolog
scrapy crawl multi_spider -a url='https://www.glorybee.com' -a domain='glorybee.com' -O .\files\GloryBee.csv --nolog
scrapy crawl multi_spider -a url='https://www.glucorp.com' -a domain='glucorp.com' -O .\files\GluCorp.csv --nolog
scrapy crawl multi_spider -a url='https://www.gmplabs.com' -a domain='gmplabs.com' -O .\files\GMPLaboratoriesofAmerica,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.gnusante.com' -a domain='gnusante.com' -O .\files\GnuSanteCreations.csv --nolog
scrapy crawl multi_spider -a url='https://www.godshalls.com' -a domain='godshalls.com' -O .\files\Godshall'sQualityMeats.csv --nolog
scrapy crawl multi_spider -a url='https://www.goedomega3.com' -a domain='goedomega3.com' -O .\files\GOEDOmega3.csv --nolog
scrapy crawl multi_spider -a url='https://www.gomacro.com' -a domain='gomacro.com' -O .\files\GoMacro.csv --nolog
scrapy crawl multi_spider -a url='https://www.franzbakery.com' -a domain='franzbakery.com' -O .\files\KetoCultureBaking.csv --nolog
scrapy crawl multi_spider -a url='https://www.kevinsnaturalfoods.com/' -a domain='kevinsnaturalfoods.com/' -O .\files\Kevin'sNaturalFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.kibofoods.com' -a domain='kibofoods.com' -O .\files\KiboFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.killcliff.com' -a domain='killcliff.com' -O .\files\KillCliff,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kingarthurbaking.com' -a domain='kingarthurbaking.com' -O .\files\KingArthurBakingCompany.csv --nolog
scrapy crawl multi_spider -a url='https://www.kinnikinnick.com' -a domain='kinnikinnick.com' -O .\files\KinnikinnickFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.kinomega.com' -a domain='kinomega.com' -O .\files\KinOmegaBiopharmInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kizeconcepts.com' -a domain='kizeconcepts.com' -O .\files\KiZEConcepts.csv --nolog
scrapy crawl multi_spider -a url='https://www.kaijaerice.com/' -a domain='kaijaerice.com/' -O .\files\KJWORLDFOODSCO.,LTD..csv --nolog
scrapy crawl multi_spider -a url='https://www.kleankanteen.com' -a domain='kleankanteen.com' -O .\files\KleanKanteen.csv --nolog
scrapy crawl multi_spider -a url='https://www.konscious.com' -a domain='konscious.com' -O .\files\KonsciousFoodsInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.korshots.com' -a domain='korshots.com' -O .\files\KorShots.csv --nolog
scrapy crawl multi_spider -a url='https://www.at.or.kr' -a domain='at.or.kr' -O .\files\KoreaAgro-TradeCenter.csv --nolog
scrapy crawl multi_spider -a url='https://www.kronchy.us' -a domain='kronchy.us' -O .\files\Kronchy.csv --nolog
scrapy crawl multi_spider -a url='https://www.ksfintl.com/' -a domain='ksfintl.com/' -O .\files\KSFCO.,LTD.csv --nolog
scrapy crawl multi_spider -a url='https://www.ixoreal.com' -a domain='ixoreal.com' -O .\files\KSM-66Ashwagandha.csv --nolog
scrapy crawl multi_spider -a url='https://www.kyowa-usa.com' -a domain='kyowa-usa.com' -O .\files\KyowaHakkoUSA.csv --nolog
scrapy crawl multi_spider -a url='https://www.lafinesse.es' -a domain='lafinesse.es' -O .\files\LaFinesseTruffles.csv --nolog
scrapy crawl multi_spider -a url='https://www.lacroixwater.com' -a domain='lacroixwater.com' -O .\files\LaCroixSparklingWater.csv --nolog
scrapy crawl multi_spider -a url='https://www.lafes.com' -a domain='lafes.com' -O .\files\Lafe'sNaturalBodyCare.csv --nolog
scrapy crawl multi_spider -a url='https://www.lairdsuperfood.com' -a domain='lairdsuperfood.com' -O .\files\LairdSuperfood.csv --nolog
scrapy crawl multi_spider -a url='https://www.laobandumplings.com' -a domain='laobandumplings.com' -O .\files\LaobanDumplings.csv --nolog
scrapy crawl multi_spider -a url='https://www.lastobject.com' -a domain='lastobject.com' -O .\files\LastObject.csv --nolog
scrapy crawl multi_spider -a url='https://www.lattini.com' -a domain='lattini.com' -O .\files\Lattini,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.launchfulfillment.com' -a domain='launchfulfillment.com' -O .\files\LaunchFulfillment.csv --nolog
scrapy crawl multi_spider -a url='https://www.lebbysnacks.com' -a domain='lebbysnacks.com' -O .\files\LebbySnacks.csv --nolog
scrapy crawl multi_spider -a url='https://www.lemurinc.com' -a domain='lemurinc.com' -O .\files\LemurInternational,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.lesserevil.com' -a domain='lesserevil.com' -O .\files\LesserEvil,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.lettherebehempfoods.com' -a domain='lettherebehempfoods.com' -O .\files\LetThereBeHemp.csv --nolog
scrapy crawl multi_spider -a url='https://www.lewisroadcreamery.co.nz' -a domain='lewisroadcreamery.co.nz' -O .\files\LewisRoadCreameryLimited.csv --nolog
scrapy crawl multi_spider -a url='https://www.hempseed.cn' -a domain='hempseed.cn' -O .\files\LiaoningQiaopaiBiotechCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.lifebridgeintl.com' -a domain='lifebridgeintl.com' -O .\files\LIFEBRIDGEINTERNATIONAL.csv --nolog
scrapy crawl multi_spider -a url='https://www.cleanprene.com/' -a domain='cleanprene.com/' -O .\files\LifeWearTechnologies,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.lifeaidbevco.com' -a domain='lifeaidbevco.com' -O .\files\LIFEAIDBEVERAGECOMPANY.csv --nolog
scrapy crawl multi_spider -a url='https://www.lifewaykefir.com' -a domain='lifewaykefir.com' -O .\files\LifewayFoods,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.lovelilbucks.com' -a domain='lovelilbucks.com' -O .\files\LilBucks,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.lilyofthedesert.com' -a domain='lilyofthedesert.com' -O .\files\LilyoftheDesert.csv --nolog
scrapy crawl multi_spider -a url='https://www.limbua-group.com/en' -a domain='limbua-group.com/en' -O .\files\LIMBUADeutschlandGmbH.csv --nolog
scrapy crawl multi_spider -a url='https://www.liquadry.com' -a domain='liquadry.com' -O .\files\LiquaDryInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.liquid-iv.com' -a domain='liquid-iv.com' -O .\files\LiquidI.V..csv --nolog
scrapy crawl multi_spider -a url='https://www.coffeelgc.com' -a domain='coffeelgc.com' -O .\files\LittleGreenCyclo.csv --nolog
scrapy crawl multi_spider -a url='https://www.littlemoonessentials.com' -a domain='littlemoonessentials.com' -O .\files\LittleMoonEssentials.csv --nolog
scrapy crawl multi_spider -a url='https://www.littlesecretschocolates.com' -a domain='littlesecretschocolates.com' -O .\files\LittleSecretsChocolates.csv --nolog
scrapy crawl multi_spider -a url='https://www.livekuna.com' -a domain='livekuna.com' -O .\files\LiveKuna.csv --nolog
scrapy crawl multi_spider -a url='https://www.livelyupyourbreath.com' -a domain='livelyupyourbreath.com' -O .\files\LivelyUpYourBreath,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.rcherbals.com' -a domain='rcherbals.com' -O .\files\RidgeCrestHerbals.csv --nolog
scrapy crawl multi_spider -a url='https://www.savannahbee.com' -a domain='savannahbee.com' -O .\files\SavannahBeeCompany.csv --nolog
scrapy crawl multi_spider -a url='https://www.sealtheseasons.com' -a domain='sealtheseasons.com' -O .\files\SealtheSeasons.csv --nolog
scrapy crawl multi_spider -a url='https://www.sentrymanufacturing.net' -a domain='sentrymanufacturing.net' -O .\files\SentryManufacturing,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.sdrxsw.com' -a domain='sdrxsw.com' -O .\files\ShandongRunxinBiotechnologyCo.,Ltd.csv --nolog
scrapy crawl multi_spider -a url='https://www.sierranevadacheese.com' -a domain='sierranevadacheese.com' -O .\files\SierraNevadaCheeseCo..csv --nolog
scrapy crawl multi_spider -a url='https://www.smartypantsvitamins.com' -a domain='smartypantsvitamins.com' -O .\files\SmartyPantsVitamins.csv --nolog
scrapy crawl multi_spider -a url='https://www.smpnutra.com' -a domain='smpnutra.com' -O .\files\SMPNutra.csv --nolog
scrapy crawl multi_spider -a url='https://www.soft-gel.com' -a domain='soft-gel.com' -O .\files\SoftGelTechnologies,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.spinstersistersco.com' -a domain='spinstersistersco.com' -O .\files\SpinsterSistersCo..csv --nolog
scrapy crawl multi_spider -a url='https://www.sukuvitamins.com' -a domain='sukuvitamins.com' -O .\files\SUKUVITAMINS.csv --nolog
scrapy crawl multi_spider -a url='https://www.sunchlorellausa.com' -a domain='sunchlorellausa.com' -O .\files\SunChlorellaUSA.csv --nolog
scrapy crawl multi_spider -a url='https://www.sunfood.com' -a domain='sunfood.com' -O .\files\SunfoodSuperfoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.sunridgefarms.com' -a domain='sunridgefarms.com' -O .\files\SunRidgeFarms.csv --nolog
scrapy crawl multi_spider -a url='https://www.svz.com' -a domain='svz.com' -O .\files\SVZUSAWashington,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.teeccino.com' -a domain='teeccino.com' -O .\files\Teeccino.csv --nolog
scrapy crawl multi_spider -a url='https://www.thaicoconut.com' -a domain='thaicoconut.com' -O .\files\ThaiCoconutPublicCompanyLimited.csv --nolog
scrapy crawl multi_spider -a url='https://www.safeandfair.com' -a domain='safeandfair.com' -O .\files\TheSafe+FairFoodCompany.csv --nolog
scrapy crawl multi_spider -a url='https://www.unscentedco.com' -a domain='unscentedco.com' -O .\files\TheUnscentedCompany.csv --nolog
scrapy crawl multi_spider -a url='https://www.threefarmdaughters.com' -a domain='threefarmdaughters.com' -O .\files\ThreeFarmDaughters.csv --nolog
scrapy crawl multi_spider -a url='https://www.tinysproutsfoods.com' -a domain='tinysproutsfoods.com' -O .\files\TinySproutsFoodsInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.topseedz.com' -a domain='topseedz.com' -O .\files\TopSeedzLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.traceminerals.com' -a domain='traceminerals.com' -O .\files\TraceMineralsResearch.csv --nolog
scrapy crawl multi_spider -a url='https://www.twinlab.com' -a domain='twinlab.com' -O .\files\TwinlabConsolidationCorporation.csv --nolog
scrapy crawl multi_spider -a url='https://www.twrlmilktea.com' -a domain='twrlmilktea.com' -O .\files\TwrlMilkTea.csv --nolog
scrapy crawl multi_spider -a url='https://www.unclematts.com' -a domain='unclematts.com' -O .\files\UncleMatt'sOrganic.csv --nolog
scrapy crawl multi_spider -a url='https://www.upcycledfood.org' -a domain='upcycledfood.org' -O .\files\UpcycledFoodAssociation.csv --nolog
scrapy crawl multi_spider -a url='https://www.utivahealth.com' -a domain='utivahealth.com' -O .\files\UtivaHealth.csv --nolog
scrapy crawl multi_spider -a url='https://www.vevanfoods.com' -a domain='vevanfoods.com' -O .\files\VevanFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.vitacup.com' -a domain='vitacup.com' -O .\files\VitaCup,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.vitaminfriends.com' -a domain='vitaminfriends.com' -O .\files\VitaminFriends.csv --nolog
scrapy crawl multi_spider -a url='https://www.vitanica.com' -a domain='vitanica.com' -O .\files\Vitanica.csv --nolog
scrapy crawl multi_spider -a url='https://www.vytalogy.com' -a domain='vytalogy.com' -O .\files\VytalogyWellness.csv --nolog
scrapy crawl multi_spider -a url='https://www.kyolic.com' -a domain='kyolic.com' -O .\files\WakunagaofAmerica.csv --nolog
scrapy crawl multi_spider -a url='https://www.westcoastnaturals.com' -a domain='westcoastnaturals.com' -O .\files\WCNBioTechInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.wholefoodsmagazine.com' -a domain='wholefoodsmagazine.com' -O .\files\WholeFoodsMagazine.csv --nolog
scrapy crawl multi_spider -a url='https://www.wildtonic.com' -a domain='wildtonic.com' -O .\files\WildTonicJunKombucha.csv --nolog
scrapy crawl multi_spider -a url='https://www.wildbrine.com' -a domain='wildbrine.com' -O .\files\wildbrine,wildCREAMERY.csv --nolog
scrapy crawl multi_spider -a url='https://www.wishgardenherbs.com' -a domain='wishgardenherbs.com' -O .\files\WishGardenHerbs.csv --nolog
scrapy crawl multi_spider -a url='https://www.athleticism.com' -a domain='athleticism.com' -O .\files\ATHLETICISMLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.atlanticseafarms.com' -a domain='atlanticseafarms.com' -O .\files\AtlanticSeaFarms.csv --nolog
scrapy crawl multi_spider -a url='https://www.biovanta.com' -a domain='biovanta.com' -O .\files\Biovanta.csv --nolog
scrapy crawl multi_spider -a url='https://www.chickapea.com' -a domain='chickapea.com' -O .\files\Chickapea.csv --nolog
scrapy crawl multi_spider -a url='https://www.dailycrunchsnacks.com' -a domain='dailycrunchsnacks.com' -O .\files\DailyCrunch.csv --nolog
scrapy crawl multi_spider -a url='https://www.danonenorthamerica.com' -a domain='danonenorthamerica.com' -O .\files\DanoneNorthAmerica.csv --nolog
scrapy crawl multi_spider -a url='https://www.danosseasoning.com' -a domain='danosseasoning.com' -O .\files\Dan-O'sSeasoning.csv --nolog
scrapy crawl multi_spider -a url='https://www.dragonherbs.com' -a domain='dragonherbs.com' -O .\files\DragonHerbs.csv --nolog
scrapy crawl multi_spider -a url='https://www.ecoideas.ca' -a domain='ecoideas.ca' -O .\files\Ecoideas.csv --nolog
scrapy crawl multi_spider -a url='https://www.fruitforthought.com' -a domain='fruitforthought.com' -O .\files\FruitForThought.csv --nolog
scrapy crawl multi_spider -a url='https://www.furtherfood.com' -a domain='furtherfood.com' -O .\files\FurtherFood.csv --nolog
scrapy crawl multi_spider -a url='https://www.gnosisbylesaffre.com' -a domain='gnosisbylesaffre.com' -O .\files\GnosisbyLesaffre.csv --nolog
scrapy crawl multi_spider -a url='https://www.khongguan.com' -a domain='khongguan.com' -O .\files\KhongGuanCorporation.csv --nolog
scrapy crawl multi_spider -a url='https://www.kidfresh.com/' -a domain='kidfresh.com/' -O .\files\KIDFRESH.csv --nolog
scrapy crawl multi_spider -a url='https://www.littletwig.com' -a domain='littletwig.com' -O .\files\KittrichCorporation.csv --nolog
scrapy crawl multi_spider -a url='https://www.koko-organics.com' -a domain='koko-organics.com' -O .\files\KokoOil.csv --nolog
scrapy crawl multi_spider -a url='https://www.kokomio.com' -a domain='kokomio.com' -O .\files\Kokomio.csv --nolog
scrapy crawl multi_spider -a url='https://www.lalibations.com/' -a domain='lalibations.com/' -O .\files\L.A.Libations.csv --nolog
scrapy crawl multi_spider -a url='https://www.lamonarcabakery.com' -a domain='lamonarcabakery.com' -O .\files\LaMonarcaBakery.csv --nolog
scrapy crawl multi_spider -a url='https://www.latortillafactory.com' -a domain='latortillafactory.com' -O .\files\LaTortillaFactory.csv --nolog
scrapy crawl multi_spider -a url='https://www.lakeviewfarms.com/' -a domain='lakeviewfarms.com/' -O .\files\LakeviewFarms.csv --nolog
scrapy crawl multi_spider -a url='https://www.eatlegendary.com' -a domain='eatlegendary.com' -O .\files\LegendaryFoods,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.lifeseasons.com' -a domain='lifeseasons.com' -O .\files\LifeSeasons,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.lifestraw.com' -a domain='lifestraw.com' -O .\files\LifeStraw.csv --nolog
scrapy crawl multi_spider -a url='https://www.majesticbutter.com/' -a domain='majesticbutter.com/' -O .\files\LiveMajestic.csv --nolog
scrapy crawl multi_spider -a url='https://www.savorbysuzie.com' -a domain='savorbysuzie.com' -O .\files\SavorStreetFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.similasanusa.com' -a domain='similasanusa.com' -O .\files\Similasan.csv --nolog
scrapy crawl multi_spider -a url='https://www.simplemills.com' -a domain='simplemills.com' -O .\files\SimpleMills,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.simplyfuel.com' -a domain='simplyfuel.com' -O .\files\simplyFUEL.csv --nolog
scrapy crawl multi_spider -a url='https://www.smartjuice.us' -a domain='smartjuice.us' -O .\files\SmartJuice.csv --nolog
scrapy crawl multi_spider -a url='https://www.sunshinenutrition.us' -a domain='sunshinenutrition.us' -O .\files\SUNSHINENUTRITIONL.L.C.csv --nolog
scrapy crawl multi_spider -a url='https://www.sweegen.com' -a domain='sweegen.com' -O .\files\SweeGen.csv --nolog
scrapy crawl multi_spider -a url='https://www.drinkwildwonder.com' -a domain='drinkwildwonder.com' -O .\files\wildwonder.csv --nolog
scrapy crawl multi_spider -a url='https://www.youtheory.com' -a domain='youtheory.com' -O .\files\Youtheory.csv --nolog
scrapy crawl multi_spider -a url='https://www.bigelowtea.com' -a domain='bigelowtea.com' -O .\files\BigelowTea.csv --nolog
scrapy crawl multi_spider -a url='https://www.biokleenhome.com' -a domain='biokleenhome.com' -O .\files\Biokleen.csv --nolog
scrapy crawl multi_spider -a url='https://www.bodyhealth.com' -a domain='bodyhealth.com' -O .\files\BodyHealth.csv --nolog
scrapy crawl multi_spider -a url='https://www.dosabydosa.com' -a domain='dosabydosa.com' -O .\files\dosabyDOSA.csv --nolog
scrapy crawl multi_spider -a url='https://www.fertin.com' -a domain='fertin.com' -O .\files\FertinPharma.csv --nolog
scrapy crawl multi_spider -a url='https://www.forcesofnaturemedicine.com' -a domain='forcesofnaturemedicine.com' -O .\files\ForcesofNature.csv --nolog
scrapy crawl multi_spider -a url='https://www.goli.com' -a domain='goli.com' -O .\files\GoliNutritionInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.mykiddiwinks.com' -a domain='mykiddiwinks.com' -O .\files\KiddiwinksInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kodiakcakes.com' -a domain='kodiakcakes.com' -O .\files\KodiakCakes.csv --nolog
scrapy crawl multi_spider -a url='https://www.kokada.com' -a domain='kokada.com' -O .\files\Kokada.csv --nolog
scrapy crawl multi_spider -a url='https://www.kgcus.com' -a domain='kgcus.com' -O .\files\KoreaGinsengCorp..csv --nolog
scrapy crawl multi_spider -a url='https://www.cutlery.kyocera.com/' -a domain='cutlery.kyocera.com/' -O .\files\KyoceraInternational,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.wholesale.lanternpress.com' -a domain='wholesale.lanternpress.com' -O .\files\LanternPress,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.lettucegrow.com/' -a domain='lettucegrow.com/' -O .\files\LettuceGrow.csv --nolog
scrapy crawl multi_spider -a url='https://www.liquiddeath.com' -a domain='liquiddeath.com' -O .\files\LiquidDeath.csv --nolog
scrapy crawl multi_spider -a url='https://www.remedydrinks.com' -a domain='remedydrinks.com' -O .\files\RemedyDrinks.csv --nolog
scrapy crawl multi_spider -a url='https://www.sabinsa.com' -a domain='sabinsa.com' -O .\files\SABINSA.csv --nolog
scrapy crawl multi_spider -a url='https://www.sparkle.life' -a domain='sparkle.life' -O .\files\SparkleInnovationsInc.csv --nolog
scrapy crawl multi_spider -a url='https://www.bcfoods.com' -a domain='bcfoods.com' -O .\files\BCFoods,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.belbrandsusa.com' -a domain='belbrandsusa.com' -O .\files\BelBrands.csv --nolog
scrapy crawl multi_spider -a url='https://www.compoundsolutions.com' -a domain='compoundsolutions.com' -O .\files\CompoundSolutions,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.epacflexibles.com' -a domain='epacflexibles.com' -O .\files\ePacFlexiblePackaging.csv --nolog
scrapy crawl multi_spider -a url='https://www.lapreferida.com' -a domain='lapreferida.com' -O .\files\LaPreferida.csv --nolog
scrapy crawl multi_spider -a url='https://www.layncorp.com' -a domain='layncorp.com' -O .\files\LaynNaturalIngredients.csv --nolog
scrapy crawl multi_spider -a url='https://www.simplydelish.net' -a domain='simplydelish.net' -O .\files\SimplyDelish.csv --nolog
scrapy crawl multi_spider -a url='https://www.sofrescousa.com' -a domain='sofrescousa.com' -O .\files\Sofresco.csv --nolog
scrapy crawl multi_spider -a url='https://www.sunwarrior.com' -a domain='sunwarrior.com' -O .\files\Sunwarrior.csv --nolog
scrapy crawl multi_spider -a url='https://www.thefoodmovement.com' -a domain='thefoodmovement.com' -O .\files\THEFOODMOVEMENTCO..csv --nolog
scrapy crawl multi_spider -a url='https://www.gardenoflife.com' -a domain='gardenoflife.com' -O .\files\GardenofLife.csv --nolog
scrapy crawl multi_spider -a url='https://www.lilliesq.com/' -a domain='lilliesq.com/' -O .\files\Lillie'sQ.csv --nolog
scrapy crawl multi_spider -a url='https://www.vitality.ca' -a domain='vitality.ca' -O .\files\VitalityProductsInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.corefoods.com' -a domain='corefoods.com' -O .\files\COREFOODS.csv --nolog
scrapy crawl multi_spider -a url='https://www.ketofoods.com' -a domain='ketofoods.com' -O .\files\KetoFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.lakanto.com' -a domain='lakanto.com' -O .\files\Lakanto.csv --nolog
scrapy crawl multi_spider -a url='https://www.lanxess.com' -a domain='lanxess.com' -O .\files\LanxessCorporation.csv --nolog
scrapy crawl multi_spider -a url='https://www.likeairsnacks.com' -a domain='likeairsnacks.com' -O .\files\LikeAir.csv --nolog
scrapy crawl multi_spider -a url='https://www.ashland.com' -a domain='ashland.com' -O .\files\Ashland.csv --nolog
scrapy crawl multi_spider -a url='https://www.bioray.com' -a domain='bioray.com' -O .\files\BIORAY.csv --nolog
scrapy crawl multi_spider -a url='https://www.cleancause.com' -a domain='cleancause.com' -O .\files\CLEANCause.csv --nolog
scrapy crawl multi_spider -a url='https://www.latourangelle.com' -a domain='latourangelle.com' -O .\files\LaTourangelle.csv --nolog
scrapy crawl multi_spider -a url='https://www.ribus.com' -a domain='ribus.com' -O .\files\RIBUS,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.sunsweet.com' -a domain='sunsweet.com' -O .\files\Sunsweet.csv --nolog
scrapy crawl multi_spider -a url='https://www.beneo.com' -a domain='beneo.com' -O .\files\BENEO.csv --nolog
scrapy crawl multi_spider -a url='https://www.bio-cat.com' -a domain='bio-cat.com' -O .\files\BIO-CAT.csv --nolog
scrapy crawl multi_spider -a url='https://www.bluebuffalo.com' -a domain='bluebuffalo.com' -O .\files\BlueBuffalo.csv --nolog
scrapy crawl multi_spider -a url='https://www.bluestar.global' -a domain='bluestar.global' -O .\files\BlueStarCorp.csv --nolog
scrapy crawl multi_spider -a url='https://www.eatbobos.com' -a domain='eatbobos.com' -O .\files\Bobo's.csv --nolog
scrapy crawl multi_spider -a url='https://www.boironusa.com' -a domain='boironusa.com' -O .\files\Boiron.csv --nolog
scrapy crawl multi_spider -a url='https://www.bulletproof.com' -a domain='bulletproof.com' -O .\files\Bulletproof.csv --nolog
scrapy crawl multi_spider -a url='https://www.bintergroups.com' -a domain='bintergroups.com' -O .\files\BusinessInternationalGroup.csv --nolog
scrapy crawl multi_spider -a url='https://www.culinayogurt.com' -a domain='culinayogurt.com' -O .\files\Culina.csv --nolog
scrapy crawl multi_spider -a url='https://www.eatdeux.com' -a domain='eatdeux.com' -O .\files\DEUX.csv --nolog
scrapy crawl multi_spider -a url='https://www.elsenutrition.com' -a domain='elsenutrition.com' -O .\files\ElseNutrition.csv --nolog
scrapy crawl multi_spider -a url='https://www.thisisembody.com' -a domain='thisisembody.com' -O .\files\Embody.csv --nolog
scrapy crawl multi_spider -a url='https://www.emeraldlabs.com' -a domain='emeraldlabs.com' -O .\files\EmeraldLabs.csv --nolog
scrapy crawl multi_spider -a url='https://www.emergenc.com' -a domain='emergenc.com' -O .\files\Emergen-C.csv --nolog
scrapy crawl multi_spider -a url='https://www.florahealth.com' -a domain='florahealth.com' -O .\files\Flora,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.gencorpacific.com' -a domain='gencorpacific.com' -O .\files\Gencor.csv --nolog
scrapy crawl multi_spider -a url='https://www.gerber.com' -a domain='gerber.com' -O .\files\Gerber.csv --nolog
scrapy crawl multi_spider -a url='https://www.goodculture.com' -a domain='goodculture.com' -O .\files\GoodCulture.csv --nolog
scrapy crawl multi_spider -a url='https://www.kerry.com' -a domain='kerry.com' -O .\files\Kerry,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kevala.net' -a domain='kevala.net' -O .\files\Kevala.csv --nolog
scrapy crawl multi_spider -a url='https://www.mykitsch.com' -a domain='mykitsch.com' -O .\files\KitschLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.kiwalife.com' -a domain='kiwalife.com' -O .\files\Kiwa.csv --nolog
scrapy crawl multi_spider -a url='https://www.koopsmustard.com/' -a domain='koopsmustard.com/' -O .\files\Koops.csv --nolog
scrapy crawl multi_spider -a url='https://www.lacolombe.com' -a domain='lacolombe.com' -O .\files\LaColombe.csv --nolog
scrapy crawl multi_spider -a url='https://wwww.lapastainc.com' -a domain='.lapastainc.com' -O .\files\LaPasta,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.laurelfoods.com' -a domain='laurelfoods.com' -O .\files\LaurelFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.lovelegrand.com/' -a domain='lovelegrand.com/' -O .\files\LeGrand.csv --nolog
scrapy crawl multi_spider -a url='https://www.lechia.co' -a domain='lechia.co' -O .\files\Lechia.csv --nolog
scrapy crawl multi_spider -a url='https://www.lennoxpets.com' -a domain='lennoxpets.com' -O .\files\Lennox.csv --nolog
scrapy crawl multi_spider -a url='https://www.lifeextension.com' -a domain='lifeextension.com' -O .\files\LifeExtension.csv --nolog
scrapy crawl multi_spider -a url='https://www.linhardt.com/en' -a domain='linhardt.com/en' -O .\files\LinhardtGroup.csv --nolog
scrapy crawl multi_spider -a url='https://www.redmond.life' -a domain='redmond.life' -O .\files\Redmond.csv --nolog
scrapy crawl multi_spider -a url='https://www.drinksanzo.com' -a domain='drinksanzo.com' -O .\files\Sanzo.csv --nolog
scrapy crawl multi_spider -a url='https://www.solgar.com' -a domain='solgar.com' -O .\files\Solgar,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.sosishealthypleasures.com' -a domain='sosishealthypleasures.com' -O .\files\Sosi's.csv --nolog
scrapy crawl multi_spider -a url='https://www.spins.com' -a domain='spins.com' -O .\files\SPINS.csv --nolog
scrapy crawl multi_spider -a url='https://www.nestle.com' -a domain='nestle.com' -O .\files\Starbucks.csv --nolog
scrapy crawl multi_spider -a url='https://www.tosi.com' -a domain='tosi.com' -O .\files\Tosi.csv --nolog
scrapy crawl multi_spider -a url='https://www.tribest.com' -a domain='tribest.com' -O .\files\Tribest.csv --nolog
scrapy crawl multi_spider -a url='https://www.myvega.com' -a domain='myvega.com' -O .\files\Vega.csv --nolog
scrapy crawl multi_spider -a url='https://www.drinkvina.com' -a domain='drinkvina.com' -O .\files\Vina.csv --nolog
scrapy crawl multi_spider -a url='https://www.madeinnature.com' -a domain='madeinnature.com' -O .\files\WildWest.csv --nolog
scrapy crawl multi_spider -a url='https://www.yoursuper.com' -a domain='yoursuper.com' -O .\files\YourSuper.csv --nolog
scrapy crawl multi_spider -a url='https://www.helloyumi.com' -a domain='helloyumi.com' -O .\files\YUMI.csv --nolog
scrapy crawl multi_spider -a url='https://www.zico.com' -a domain='zico.com' -O .\files\ZICO.csv --nolog
scrapy crawl multi_spider -a url='https://www.anaislife.com' -a domain='anaislife.com' -O .\files\AnaisLife,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.analyticalresource.com' -a domain='analyticalresource.com' -O .\files\AnalyticalResourceLaboratories(ARL).csv --nolog
scrapy crawl multi_spider -a url='https://www.waimeli.com' -a domain='waimeli.com' -O .\files\BigIslandMoonbowFarmsL.L.C..csv --nolog
scrapy crawl multi_spider -a url='https://www.bioptimizers.com' -a domain='bioptimizers.com' -O .\files\BiOptimizersUSA,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kefiplant.com' -a domain='kefiplant.com' -O .\files\BIORAbyKefiplant.csv --nolog
scrapy crawl multi_spider -a url='https://www.bobsredmill.com' -a domain='bobsredmill.com' -O .\files\Bob'sRedMillNaturalFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.brainiacfoods.com' -a domain='brainiacfoods.com' -O .\files\BrainiacFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.brewdrkombucha.com' -a domain='brewdrkombucha.com' -O .\files\BrewDr.Kombucha.csv --nolog
scrapy crawl multi_spider -a url='https://www.bunjie.com' -a domain='bunjie.com' -O .\files\BunjiePtyLtd.csv --nolog
scrapy crawl multi_spider -a url='https://www.carlsonlabs.com' -a domain='carlsonlabs.com' -O .\files\CarlsonLaboratories,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.casademesquite.com' -a domain='casademesquite.com' -O .\files\CASADEMESQUITEARGENTINASRL.csv --nolog
scrapy crawl multi_spider -a url='https://www.catalo.com' -a domain='catalo.com' -O .\files\CATALONaturals,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.catherych.com' -a domain='catherych.com' -O .\files\CatherychInc.csv --nolog
scrapy crawl multi_spider -a url='https://www.cosmos-standard.org' -a domain='cosmos-standard.org' -O .\files\COSMOS-standard.csv --nolog
scrapy crawl multi_spider -a url='https://www.designerwellness.com' -a domain='designerwellness.com' -O .\files\DesignerProtein,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.drgingers.com' -a domain='drgingers.com' -O .\files\DrGinger'sHealthcareProductsLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.drkellyann.com' -a domain='drkellyann.com' -O .\files\Dr.Kellyann.csv --nolog
scrapy crawl multi_spider -a url='https://www.dudeproducts.com' -a domain='dudeproducts.com' -O .\files\DUDEPRODUCTSINC..csv --nolog
scrapy crawl multi_spider -a url='https://www.emirelli.com' -a domain='emirelli.com' -O .\files\EmirelliSanFrancisco.csv --nolog
scrapy crawl multi_spider -a url='https://www.epicorimmune.com' -a domain='epicorimmune.com' -O .\files\EpiCorPostbiotic(aCargillbrand).csv --nolog
scrapy crawl multi_spider -a url='https://www.fantasty-foods.com' -a domain='fantasty-foods.com' -O .\files\Fan-TastyFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.farlong.com' -a domain='farlong.com' -O .\files\FarlongNutraceutical.csv --nolog
scrapy crawl multi_spider -a url='https://www.fodyfoods.com' -a domain='fodyfoods.com' -O .\files\FODYFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.fujicapsule.com' -a domain='fujicapsule.com' -O .\files\FujiCapsuleCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.organictattva.com' -a domain='organictattva.com' -O .\files\GlobalAgroCommodities,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.exberry.com' -a domain='exberry.com' -O .\files\GNTUSA.csv --nolog
scrapy crawl multi_spider -a url='https://www.snacksfromthesea.com' -a domain='snacksfromthesea.com' -O .\files\KelpieChips.csv --nolog
scrapy crawl multi_spider -a url='https://www.khalsasalsa.net' -a domain='khalsasalsa.net' -O .\files\KhalsaSalsa-KhalsaKitchen.csv --nolog
scrapy crawl multi_spider -a url='https://www.kimino.com' -a domain='kimino.com' -O .\files\KiminoDrinksInc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kimnoriusa.com' -a domain='kimnoriusa.com' -O .\files\KimnoriUSA,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kingping.com.tw' -a domain='kingping.com.tw' -O .\files\KingPingTea,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.kendelteas.com' -a domain='kendelteas.com' -O .\files\KIRK-FPCARI-MEDINTERNATIONALDIVISION.csv --nolog
scrapy crawl multi_spider -a url='https://www.ksfs.co.kr' -a domain='ksfs.co.kr' -O .\files\KKOHShaemFoodCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.koda.com.tw' -a domain='koda.com.tw' -O .\files\KoDaPharmaceuticalCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.drinkkoe.com' -a domain='drinkkoe.com' -O .\files\KoeKombucha.csv --nolog
scrapy crawl multi_spider -a url='https://www.kooshy.com/' -a domain='kooshy.com/' -O .\files\KooshyCroutons.csv --nolog
scrapy crawl multi_spider -a url='https://www.hanyinhong.co.kr' -a domain='hanyinhong.co.kr' -O .\files\KOREAHANYINHONGCO.,LTD.csv --nolog
scrapy crawl multi_spider -a url='https://www.chefscutrealjerky.com' -a domain='chefscutrealjerky.com' -O .\files\KRAVEPureFoods/Chef'sCutRealJerky.csv --nolog
scrapy crawl multi_spider -a url='https://www.krishnaenzytech.com' -a domain='krishnaenzytech.com' -O .\files\KrishnaEnzytechPvt.Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.kruyu.com' -a domain='kruyu.com' -O .\files\KruYuCottageCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.kulikulifoods.com' -a domain='kulikulifoods.com' -O .\files\KuliKuliFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.lanogalera.com' -a domain='lanogalera.com' -O .\files\LANOGALERAUSA,INC..csv --nolog
scrapy crawl multi_spider -a url='https://www.lafaza.com' -a domain='lafaza.com' -O .\files\LAFAZAFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.lakewoodorganic.com' -a domain='lakewoodorganic.com' -O .\files\LakewoodOrganicJuiceCompany.csv --nolog
scrapy crawl multi_spider -a url='https://www.nestleusa.com' -a domain='nestleusa.com' -O .\files\LaLechera.csv --nolog
scrapy crawl multi_spider -a url='https://www.lalilab.com' -a domain='lalilab.com' -O .\files\Lalilab,Inc..csv --nolog
scrapy crawl multi_spider -a url='https://www.thundercoffeemilk.com' -a domain='thundercoffeemilk.com' -O .\files\LandO'SunLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.fczy.com' -a domain='fczy.com' -O .\files\LANZHOUFOCIPHARMACEUTICALCO.,LTD..csv --nolog
scrapy crawl multi_spider -a url='https://www.lapierremaple.com' -a domain='lapierremaple.com' -O .\files\LapierreMapleFarms.csv --nolog
scrapy crawl multi_spider -a url='https://www.larabar.com' -a domain='larabar.com' -O .\files\Larabar.csv --nolog
scrapy crawl multi_spider -a url='https://www.laurieri.com' -a domain='laurieri.com' -O .\files\LaurieriSRL.csv --nolog
scrapy crawl multi_spider -a url='https://www.lavazza.us/en_us.html' -a domain='lavazza.us/en_us.html' -O .\files\LavazzaPremiumCoffeesCorp.csv --nolog
scrapy crawl multi_spider -a url='https://www.lbbimports.com' -a domain='lbbimports.com' -O .\files\LBBDistributionInc.csv --nolog
scrapy crawl multi_spider -a url='https://www.lefoodco.com' -a domain='lefoodco.com' -O .\files\LeFoodCompany,LTD..csv --nolog
scrapy crawl multi_spider -a url='https://www.jimmytartufi.it/' -a domain='jimmytartufi.it/' -O .\files\LEVIEDELTARTUFOUSAINC..csv --nolog
scrapy crawl multi_spider -a url='https://www.lefancaps.com/' -a domain='lefancaps.com/' -O .\files\Lefancaps(Jiangsu)CompanyLtd..csv --nolog
scrapy crawl multi_spider -a url='https://www.leiraorganics.com' -a domain='leiraorganics.com' -O .\files\LEIRAOrganics.csv --nolog
scrapy crawl multi_spider -a url='https://www.encorebrands.com' -a domain='encorebrands.com' -O .\files\LemongrassFarms.csv --nolog
scrapy crawl multi_spider -a url='https://www.lemoniloramen.com' -a domain='lemoniloramen.com' -O .\files\LemoniloRamen.csv --nolog
scrapy crawl multi_spider -a url='https://www.lengdor.com' -a domain='lengdor.com' -O .\files\LengD'OrUSA,INC..csv --nolog
scrapy crawl multi_spider -a url='https://www.levainbakery.com' -a domain='levainbakery.com' -O .\files\LevainBakeryCookieCompanyLLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.lipmen.co.kr' -a domain='lipmen.co.kr' -O .\files\LipmenCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.littlenorthernbakehouse.com/' -a domain='littlenorthernbakehouse.com/' -O .\files\LittleNorthernBakehouse.csv --nolog
scrapy crawl multi_spider -a url='https://www.finaflex.com' -a domain='finaflex.com' -O .\files\REDEFINENUTRITIONdbaFINAFLEX.csv --nolog
scrapy crawl multi_spider -a url='https://www.reliancevitamin.com' -a domain='reliancevitamin.com' -O .\files\RelianceVitamin.csv --nolog
scrapy crawl multi_spider -a url='https://www.veganrobs.com' -a domain='veganrobs.com' -O .\files\Rob'sBrands,LLC.csv --nolog
scrapy crawl multi_spider -a url='https://www.ruved.com' -a domain='ruved.com' -O .\files\Ruved.csv --nolog
scrapy crawl multi_spider -a url='https://www.lakanto.com' -a domain='lakanto.com' -O .\files\SarayaCo-Packing.csv --nolog
scrapy crawl multi_spider -a url='https://www.jhdcorp.com' -a domain='jhdcorp.com' -O .\files\ShaanxiHongdaTianyuanBiochemicalCo.,Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.mycoiq.com' -a domain='mycoiq.com' -O .\files\ShroomJunkie.csv --nolog
scrapy crawl multi_spider -a url='https://www.greengoohelps.com' -a domain='greengoohelps.com' -O .\files\SierraSageHerbs.csv --nolog
scrapy crawl multi_spider -a url='https://www.growve.com' -a domain='growve.com' -O .\files\Smurfs(Growve).csv --nolog
scrapy crawl multi_spider -a url='https://www.sperofoods.co' -a domain='sperofoods.co' -O .\files\SperoFoods.csv --nolog
scrapy crawl multi_spider -a url='https://www.rm-solutions.com' -a domain='rm-solutions.com' -O .\files\SproutedPOS.csv --nolog
scrapy crawl multi_spider -a url='https://www.striveforbetter.com' -a domain='striveforbetter.com' -O .\files\StriveFREEMILKAnimal-FreeDairy.csv --nolog
scrapy crawl multi_spider -a url='https://www.timtamtummyforkids.com' -a domain='timtamtummyforkids.com' -O .\files\TimTamTummy.csv --nolog
scrapy crawl multi_spider -a url='https://www.twiningsusa.com' -a domain='twiningsusa.com' -O .\files\TwiningsofLondon.csv --nolog
scrapy crawl multi_spider -a url='https://www.vediclifesciences.com' -a domain='vediclifesciences.com' -O .\files\VedicLifesciences,(Pvt)Ltd..csv --nolog
scrapy crawl multi_spider -a url='https://www.vitaminretailer.com' -a domain='vitaminretailer.com' -O .\files\VRMMedia/VitaminRetailerMagazine.csv --nolog
scrapy crawl multi_spider -a url='https://www.waguruwelamills.com' -a domain='waguruwelamills.com' -O .\files\WaguruwelaOilMills(Pvt)Ltd.csv --nolog
scrapy crawl multi_spider -a url='https://www.mummums.com' -a domain='mummums.com' -O .\files\WantWantNorthAmerica.csv --nolog
scrapy crawl multi_spider -a url='https://www.wedderspoon.com' -a domain='wedderspoon.com' -O .\files\WedderspoonManukaHoney.csv --nolog
scrapy crawl multi_spider -a url='https://www.winsoonepoca.com' -a domain='winsoonepoca.com' -O .\files\WinSoon,Inc.DBAEpoca.csv --nolog
scrapy crawl multi_spider -a url='https://www.frusirnag.com' -a domain='frusirnag.com' -O .\files\YUENDIINGENTERPRISEINC..csv --nolog
scrapy crawl multi_spider -a url='https://www.yumvs.com' -a domain='yumvs.com' -O .\files\YumVs.csv --nolog
